### PR TITLE
Use go sdk generated from latest NITRO (12.1)

### PR DESCRIPTION
**Pull request by chiradeep**
@olljanat would you be able to test this? I don't think it will break existing `tfstate` but am not sure.

### CODE REVIEW

**Comment by olljanat** [comment]
@chiradeep sure. I tested to run terraform refresh and plan on against of our envs which this one and it did not cause any change to tfstate files (except serial number increase which is normal).

LGTM

**Comment by olljanat** [comment]
@chiradeep what is status with this one? It would be nice to get version which contains sslprofile support released and probably it is good idea to do with this one.

**Comment by chiradeep** [comment]
Some of the code needs to be regenerated. I have another developer ramping up on the code and this will be the first thing they'll be working on.

**Comment by olljanat** [comment]
@chiradeep OK. Can you then at least just release new version which contains sslprofile support as there is others waiting for it too?

**Comment by olljanat** [comment]
@chiradeep no. It only contains fix for go-nitro side.

Actual implementation was done on #21 which was merged after it.

**Pull request merged**
